name: Naukri

on:
  schedule:
    - cron: "*/5 * * * *"  
env:
  username: ${{ secrets.USERNAME }}
  password: ${{ secrets.PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install webdriver-manager selenium
          
          
      - name: execute py script # run file
        run: |
          python Naukri.py
